modLoader = "javafml"
loaderVersion = "[4,)"
license = "Apache-2.0"

[[mods]]
modId = "fabric_renderer_api_v1"

version = "1.0"
displayName = "Fabric Renderer API (CaffeineMC)"

logoFile = "sodium-icon.png" #optional

authors = "FabricMC, IMS212"

description = '''
This is a required dependency of Sodium.
'''

[[mixins]]
config = "fabric-renderer-api-v1.debughud.mixins.json"

[[mixins]]
config = "fabric-renderer-api-v1.mixins.json"